export const GET_FEATURED_PLAYLISTS_ERROR = 'GET_FEATURED_PLAYLISTS_ERROR';
export const GET_FEATURED_PLAYLISTS_REQUESTED = 'GET_FEATURED_PLAYLISTS_REQUESTED';
export const GET_FEATURED_PLAYLISTS_SUCCESS = 'GET_FEATURED_PLAYLISTS_SUCCESS';
