export const CHANGE_FILTERS_NAME_VALUE = 'CHANGE_FILTERS_NAME_VALUE';
export const GET_FILTERS_ERROR = 'GET_FILTERS_ERROR';
export const GET_FILTERS_REQUESTED = 'GET_FILTERS_REQUESTED';
export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';
