export const CHANGE_FILTER_VALUE = 'CHANGE_FILTER_VALUE';
export const GET_FILTERS_ERROR = 'GET_FILTERS_ERROR';
export const GET_FILTERS_REQUESTED = 'GET_FILTERS_REQUESTED';
export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';
